/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_MOT3.h"
#include "Left1_aliases.h"
#include "Left1.h"
#include "Left2_aliases.h"
#include "Left2.h"
#include "MotEn_aliases.h"
#include "MotEn.h"
#include "IREN_aliases.h"
#include "IREN.h"
#include "IR_aliases.h"
#include "Timer.h"
#include "Right1_aliases.h"
#include "Right1.h"
#include "Right2_aliases.h"
#include "Right2.h"
#include "Clock_Timer.h"
#include "PWM_IR.h"
#include "LEDs_aliases.h"
#include "PWM_MOT2.h"
#include "Comp1.h"
#include "Comp2.h"
#include "Comp3.h"
#include "POT_aliases.h"
#include "POT.h"
#include "VDAC1.h"
#include "VDAC2.h"
#include "VDAC3.h"
#include "PWM_MOT1.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "LED0_aliases.h"
#include "LED0.h"
#include "CyClock_100kHz.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

